--Function
CREATE FUNCTION RETURNVALUE ()
RETURNS INT
AS
	BEGIN
		RETURN 7
	END;
GO

---- IN FUNCTION MUST INCLUDE THE SCHEMA
SELECT DBO.RETURNVALUE ()

---COMMON MISTAKES; IN CREATING FUNCTION MISMATCHED DATA CREATED
CREATE FUNCTION RETURNVALUE ()
RETURNS INT
AS
	BEGIN
		RETURN 'TEST'
	END;
GO
----
--2. FIRST TIME USES RETURNS, SECOND TIME IS SINGLURE RETURN


CREATE FUNCTION RETURNVALUE ()
RETURNS INT
AS
	BEGIN
		RETURN 7
	END;
GO

----------
ALTER FUNCTION udf_FULLADD 
(
@STREET AS VARCHAR(50),
@CITY AS VARCHAR(50),
@STATE AS VARCHAR(50)
)
RETURNS VARCHAR(200)
AS
	BEGIN
		IF
			(@STREET IS NULL OR @CITY IS NULL OR @STATE IS NULL)
			RETURN 'INCOMPLETE ADDRESS'
		
		SET @STATE =
		CASE @STATE
			WHEN 'NY' THEN 'NEW YORK'
			WHEN 'VA' THEN 'VIRGINIA'
			WHEN 'DC' THEN 'DISTRICT OF COLUMBIA'
		END
		
		RETURN @STREET +'  '+@CITY +',   '+ @STATE
	END

	SELECT DBO.udf_FULLADD ('100 S AVE', 'New York','NY')


Select [AID], DBO.udf_FULLADD ([STREET], [CITY], [STATE]), [ZIPCODE]
from pub.[address]

Select [AID], DBO.udf_FULLADD ([STREET], [CITY], [STATE]), [ZIPCODE]
from pub.[address]
Where DBO.udf_FULLADD ([STREET], [CITY], [STATE]) = 'INCOMPLETE ADDRESS'

Select [AID], DBO.udf_FULLADD ([STREET], [CITY], [STATE]), [ZIPCODE]
from pub.[address]
ORder by DBO.udf_FULLADD ([STREET], [CITY], [STATE]) 

----
---Table Values Function