Use [AdventureWorks2016CTP3];
go
Select * from INFORMATION_SCHEMA.TABLES
order by TABLE_SCHEMA;
go
select * from INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE;
go
select * from INFORMATION_SCHEMA.VIEW_COLUMN_USAGE;
go
select * from INFORMATION_SCHEMA.VIEWS;
go

select * from INFORMATION_SCHEMA.SEQUENCES;
go
select * from INFORMATION_SCHEMA.DOMAINS;
go