SELECT MIN(UNITPRICE) AS MINPRICE
FROM SALES.SalesOrderDetail

SELECT ORDERQTY, LINETOTAL, UnitPrice
	from SALES.SalesOrderDetail
where UnitPrice <=1.3282;

SELECT C.ACCOUNTNUMBER, P.FIRSTNAME, P.LASTNAME
FROM SALES.CUSTOMER AS C
	INNER JOIN Person.PERSON AS P
ON C.PersonID = P.BusinessEntityID
INNER JOIN SALES.SalesOrderHeader AS SOH
ON C.CustomerID = SOH.CustomerID
WHERE EXISTS
			(SELECT SOH.ONLINEORDERFLAG FROM SALES.SALESORDERHEADER AS SOH
			WHERE C.CUSTOMERID = SOH.CUSTOMERID
			AND SOH.ONLINEORDERFLAG = 1);


WITH SALPCTE ([BusinessEntityID])
AS
	(SELECT [BusinessEntityID]
		FROM PERSON.Person)
SELECT COUNT([BusinessEntityID]) AS [BusinessEntityID]
FROM SALPCTE


WITH PERSON_NAME_CTE (BUSINESS

		SELECT * FROM ##EMPS1;

CREATE FUNCTION SALESLT.UDFTABLE (@CITY AS VARCHAR(50)) RETURNS TABLE
AS
RETURN
(SELECT City FROM SALESLT.Address
WHERE CITY = @CITY);

SELECT * FROM SalesLT.UDFTABLE ('Bellevue');