USE [master]
GO
/****** Object:  Database [NOVACAMP]    Script Date: 2/18/2018 11:35:31 AM ******/
CREATE DATABASE [NOVACAMP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NOVACAMP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLDEV2TAB\MSSQL\DATA\NOVACAMP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NOVACAMP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLDEV2TAB\MSSQL\DATA\NOVACAMP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [NOVACAMP] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NOVACAMP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NOVACAMP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NOVACAMP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NOVACAMP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NOVACAMP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NOVACAMP] SET ARITHABORT OFF 
GO
ALTER DATABASE [NOVACAMP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NOVACAMP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NOVACAMP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NOVACAMP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NOVACAMP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NOVACAMP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NOVACAMP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NOVACAMP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NOVACAMP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NOVACAMP] SET  ENABLE_BROKER 
GO
ALTER DATABASE [NOVACAMP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NOVACAMP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NOVACAMP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NOVACAMP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NOVACAMP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NOVACAMP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NOVACAMP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NOVACAMP] SET RECOVERY FULL 
GO
ALTER DATABASE [NOVACAMP] SET  MULTI_USER 
GO
ALTER DATABASE [NOVACAMP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NOVACAMP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NOVACAMP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NOVACAMP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NOVACAMP] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'NOVACAMP', N'ON'
GO
ALTER DATABASE [NOVACAMP] SET QUERY_STORE = OFF
GO
USE [NOVACAMP]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [NOVACAMP]
GO
/****** Object:  Schema [FE]    Script Date: 2/18/2018 11:35:31 AM ******/
CREATE SCHEMA [FE]
GO
/****** Object:  Schema [HR]    Script Date: 2/18/2018 11:35:31 AM ******/
CREATE SCHEMA [HR]
GO
/****** Object:  Table [HR].[EMPS]    Script Date: 2/18/2018 11:35:31 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [HR].[EMPS](
	[ID] [int] NOT NULL,
	[FIRSTNAME] [varchar](50) NOT NULL,
	[LASTNAME] [varchar](50) NOT NULL,
	[COURSEID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [NOVACAMP] SET  READ_WRITE 
GO
