--Triggers
--After Triggers

CREATE TRIGGER PUB.DEACTIV
ON PUB.AUTHOR
AFTER UPDATE
AS
BEGIN
	DECLARE @ISACTIVE AS BIT

	SELECT @ISACTIVE = ACTIVE
	FROM INSERTED

	IF (@ISACTIVE = 0)
	UPDATE PUB.AUTHOR
	SET ACTIVE = 0
	WHERE AID IN (SELECT AID FROM INSERTED)
	
	END

	drop trigger PUB.DEACTIV
	--instead of triggers

CREATE TRIGGER DBO.CATDELTE
ON DBO.CATEGORIES
	INSTEAD OF DELETE
		AS
		BEGIN	
			UPDATE CATEGORIES
			SET ACTIVE = 0
			WHERE CATEGORY IN (SELECT CATEGORYID FROM DELTED)
			END
